/**
 * Klubbmerker for spillerkortene i managerkarriere.
 *
 * Bildene ligger i public/crests og er hentet fra TheSportsDB. Merkene er
 * klubbenes egne varemerker og brukes her kun for å identifisere klubben.
 * Klubber uten merke faller tilbake til et nøytralt ikon på kortet.
 */
const crests: Record<string, string> = {
  "1. FC Köln": "/crests/1-fc-koln.png",
  "Abha": "/crests/abha.png",
  "AC Milan": "/crests/ac-milan.png",
  "AEK Athens": "/crests/aek-athens.png",
  "AFC Bournemouth": "/crests/afc-bournemouth.png",
  "Ajax": "/crests/ajax.png",
  "Al Jazira": "/crests/al-jazira.png",
  "Al-Ahli": "/crests/al-ahli.png",
  "Al-Diriyah": "/crests/al-diriyah.png",
  "Al-Duhail": "/crests/al-duhail.png",
  "Al-Fateh": "/crests/al-fateh.png",
  "Al-Hilal": "/crests/al-hilal.png",
  "Al-Ittihad": "/crests/al-ittihad.png",
  "Al-Khaleej": "/crests/al-khaleej.png",
  "Al-Nassr": "/crests/al-nassr.png",
  "Al-Qadsiah": "/crests/al-qadsiah.png",
  "Al-Rayyan": "/crests/al-rayyan.png",
  "Al-Shabab": "/crests/al-shabab.png",
  "Al-Shamal": "/crests/al-shamal.png",
  "Alavés": "/crests/alaves.png",
  "Aldosivi": "/crests/aldosivi.png",
  "Almería": "/crests/almeria.png",
  "Amed": "/crests/amed.png",
  "Anderlecht": "/crests/anderlecht.png",
  "Angers": "/crests/angers.png",
  "Aris": "/crests/aris.png",
  "Arsenal": "/crests/arsenal.png",
  "Aston Villa": "/crests/aston-villa.png",
  "Atalanta": "/crests/atalanta.png",
  "Athletic Club": "/crests/athletic-club.png",
  "Atlético Madrid": "/crests/atletico-madrid.png",
  "Atlético Mineiro": "/crests/atletico-mineiro.png",
  "Atlético Nacional": "/crests/atletico-nacional.png",
  "Augsburg": "/crests/augsburg.png",
  "Auxerre": "/crests/auxerre.png",
  "Barcelona": "/crests/barcelona.png",
  "Bayer Leverkusen": "/crests/bayer-leverkusen.png",
  "Bayern München": "/crests/bayern-munchen.png",
  "Belgrano": "/crests/belgrano.png",
  "Benfica": "/crests/benfica.png",
  "Beşiktaş": "/crests/besiktas.png",
  "Birmingham City": "/crests/birmingham-city.png",
  "Bodø/Glimt": "/crests/bodo-glimt.png",
  "Bologna": "/crests/bologna.png",
  "Borussia Dortmund": "/crests/borussia-dortmund.png",
  "Borussia Mönchengladbach": "/crests/borussia-monchengladbach.png",
  "Brentford": "/crests/brentford.png",
  "Brest": "/crests/brest.png",
  "Brighton & Hove Albion": "/crests/brighton-hove-albion.png",
  "Burnley": "/crests/burnley.png",
  "Cagliari": "/crests/cagliari.png",
  "Cardiff City": "/crests/cardiff-city.png",
  "Celta Vigo": "/crests/celta-vigo.png",
  "Celtic": "/crests/celtic.png",
  "Cerezo Osaka": "/crests/cerezo-osaka.png",
  "Chelsea": "/crests/chelsea.png",
  "Chicago Fire": "/crests/chicago-fire.png",
  "Club Brugge": "/crests/club-brugge.png",
  "Columbus Crew": "/crests/columbus-crew.png",
  "Como": "/crests/como.png",
  "Corinthians": "/crests/corinthians.png",
  "Çorum": "/crests/corum.png",
  "Coventry City": "/crests/coventry-city.png",
  "Cremonese": "/crests/cremonese.png",
  "Crvena Zvezda": "/crests/crvena-zvezda.png",
  "Crystal Palace": "/crests/crystal-palace.png",
  "Deportivo La Coruña": "/crests/deportivo-la-coruna.png",
  "Eibar": "/crests/eibar.png",
  "Eintracht Frankfurt": "/crests/eintracht-frankfurt.png",
  "Elche": "/crests/elche.png",
  "Espanyol": "/crests/espanyol.png",
  "Everton": "/crests/everton.png",
  "FC Porto": "/crests/fc-porto.png",
  "Fenerbahçe": "/crests/fenerbahce.png",
  "Feyenoord": "/crests/feyenoord.png",
  "Fiorentina": "/crests/fiorentina.png",
  "Flamengo": "/crests/flamengo.png",
  "Freiburg": "/crests/freiburg.png",
  "Frosinone": "/crests/frosinone.png",
  "Fulham": "/crests/fulham.png",
  "Galatasaray": "/crests/galatasaray.png",
  "Gençlerbirliği": "/crests/genclerbirligi.png",
  "Genoa": "/crests/genoa.png",
  "Getafe": "/crests/getafe.png",
  "Girona": "/crests/girona.png",
  "Hamburger SV": "/crests/hamburger-sv.png",
  "Heidenheim": "/crests/heidenheim.png",
  "Hellas Verona": "/crests/hellas-verona.png",
  "Hoffenheim": "/crests/hoffenheim.png",
  "Hull City": "/crests/hull-city.png",
  "Independiente": "/crests/independiente.png",
  "Inter": "/crests/inter.png",
  "Inter Miami": "/crests/inter-miami.png",
  "Internacional": "/crests/internacional.png",
  "Ipswich Town": "/crests/ipswich-town.png",
  "İstanbul Başakşehir": "/crests/istanbul-basaksehir.png",
  "Juventus": "/crests/juventus.png",
  "Konyaspor": "/crests/konyaspor.png",
  "LA Galaxy": "/crests/la-galaxy.png",
  "LAFC": "/crests/lafc.png",
  "Lazio": "/crests/lazio.png",
  "Le Havre": "/crests/le-havre.png",
  "Lecce": "/crests/lecce.png",
  "Leeds United": "/crests/leeds-united.png",
  "Lens": "/crests/lens.png",
  "Levante": "/crests/levante.png",
  "Lille": "/crests/lille.png",
  "Liverpool": "/crests/liverpool.png",
  "Lommel SK": "/crests/lommel-sk.png",
  "Lorient": "/crests/lorient.png",
  "Lyon": "/crests/lyon.png",
  "Mainz 05": "/crests/mainz-05.png",
  "Mallorca": "/crests/mallorca.png",
  "Manchester City": "/crests/manchester-city.png",
  "Manchester United": "/crests/manchester-united.png",
  "Marseille": "/crests/marseille.png",
  "Molde": "/crests/molde.png",
  "Monaco": "/crests/monaco.png",
  "Monza": "/crests/monza.png",
  "Nantes": "/crests/nantes.png",
  "Napoli": "/crests/napoli.png",
  "Neom": "/crests/neom.png",
  "Newcastle United": "/crests/newcastle-united.png",
  "Nice": "/crests/nice.png",
  "Nottingham Forest": "/crests/nottingham-forest.png",
  "Olympiacos": "/crests/olympiacos.png",
  "Orlando City": "/crests/orlando-city.png",
  "Osasuna": "/crests/osasuna.png",
  "Pachuca": "/crests/pachuca.png",
  "Paderborn": "/crests/paderborn.png",
  "Palermo": "/crests/palermo.png",
  "Palmeiras": "/crests/palmeiras.png",
  "Panathinaikos": "/crests/panathinaikos.png",
  "Paris FC": "/crests/paris-fc.png",
  "Paris Saint-Germain": "/crests/paris-saint-germain.png",
  "Parma": "/crests/parma.png",
  "Pisa": "/crests/pisa.png",
  "PSV Eindhoven": "/crests/psv-eindhoven.png",
  "Queens Park Rangers": "/crests/queens-park-rangers.png",
  "Racing Club": "/crests/racing-club.png",
  "Racing de Santander": "/crests/racing-de-santander.png",
  "Rayo Vallecano": "/crests/rayo-vallecano.png",
  "RB Leipzig": "/crests/rb-leipzig.png",
  "Real Betis": "/crests/real-betis.png",
  "Real Madrid": "/crests/real-madrid.png",
  "Real Oviedo": "/crests/real-oviedo.png",
  "Real Sociedad": "/crests/real-sociedad.png",
  "Red Bull Salzburg": "/crests/red-bull-salzburg.png",
  "Rennes": "/crests/rennes.png",
  "River Plate": "/crests/river-plate.png",
  "Rizespor": "/crests/rizespor.png",
  "Roma": "/crests/roma.png",
  "Rosario Central": "/crests/rosario-central.png",
  "Sanfrecce Hiroshima": "/crests/sanfrecce-hiroshima.png",
  "Santos": "/crests/santos.png",
  "Sassuolo": "/crests/sassuolo.png",
  "SC Braga": "/crests/sc-braga.png",
  "Schalke 04": "/crests/schalke-04.png",
  "Sevilla": "/crests/sevilla.png",
  "Sheffield United": "/crests/sheffield-united.png",
  "Southampton": "/crests/southampton.png",
  "Spartak Moscow": "/crests/spartak-moscow.png",
  "Sporting CP": "/crests/sporting-cp.png",
  "St. Pauli": "/crests/st-pauli.png",
  "Strasbourg": "/crests/strasbourg.png",
  "Stuttgart": "/crests/stuttgart.png",
  "Sunderland": "/crests/sunderland.png",
  "Teplice": "/crests/teplice.png",
  "Toluca": "/crests/toluca.png",
  "Torino": "/crests/torino.png",
  "Tottenham Hotspur": "/crests/tottenham-hotspur.png",
  "Toulouse": "/crests/toulouse.png",
  "Trabzonspor": "/crests/trabzonspor.png",
  "Udinese": "/crests/udinese.png",
  "Union Berlin": "/crests/union-berlin.png",
  "Utrecht": "/crests/utrecht.png",
  "Valencia": "/crests/valencia.png",
  "Vancouver Whitecaps": "/crests/vancouver-whitecaps.png",
  "Venezia": "/crests/venezia.png",
  "Viktoria Plzeň": "/crests/viktoria-plzen.png",
  "Villarreal": "/crests/villarreal.png",
  "Watford": "/crests/watford.png",
  "Werder Bremen": "/crests/werder-bremen.png",
  "West Ham United": "/crests/west-ham-united.png",
  "Wolfsburg": "/crests/wolfsburg.png",
  "Wolverhampton Wanderers": "/crests/wolverhampton-wanderers.png",
  "Young Boys": "/crests/young-boys.png",
};

export function clubCrest(club: string): string | null {
  return crests[club] ?? null;
}
