/**
 * Spillerbilder for kortene i managerkarriere.
 *
 * Bildene ligger i public/players og er utklipp hentet fra TheSportsDB, skalert
 * til 256 px med gjennomsiktig bakgrunn. Filnavnet er spillerens slug i
 * player_catalog, så oppslaget trenger bare å vite hvilke slugger som har bilde.
 * Spillere uten bilde faller tilbake til det nøytrale ikonet på kortet.
 */
const withPhoto = new Set([
  "abdukodir-khusanov", "ajer", "alejandro-balde", "aleksandar-pavlovic",
  "alexander-sorloth", "alisson", "amad-diallo", "andre-onana",
  "andrea-cambiaso", "andreas-christensen", "andrew-robertson", "andriy-lunin",
  "antoine-griezmann", "antoine-semenyo", "araujo", "arda-guler",
  "aursnes", "barella", "bastoni", "bellingham",
  "ben-white", "benjamin-pavard", "bernardo-silva", "boniface",
  "bradley-barcola", "brahim-diaz", "bremer", "bruno-fernandes",
  "bruno-guimaraes", "bryan-mbeumo", "caicedo", "camavinga",
  "carvajal", "casemiro", "christian-norgaard", "christian-pulisic",
  "claudio-echeverri", "clement-lenglet", "cody-gakpo", "coman",
  "conor-bradley", "courtois", "cristhian-mosquera", "cubarsi",
  "curtis-jones", "dani-olmo", "darwin-nunez", "david-alaba",
  "davide-frattesi", "davies", "dayot-upamecano", "de-bruyne",
  "de-jong", "de-ligt", "dean-huijsen", "declan-rice",
  "dembele", "denzel-dumfries", "desire-doue", "dimarco",
  "diogo-costa", "diogo-dalot", "dominik-szoboszlai", "donnarumma",
  "dovbyk", "eder-militao", "ederson", "ekitike",
  "emiliano-martinez", "endrick", "enesyri", "enzo-fernandez",
  "eric-garcia", "estevao", "ethan-nwaneri", "eze",
  "fabian-ruiz", "federico-chiesa", "felix-nmecha", "ferland-mendy",
  "fermin-lopez", "ferran-torres", "fikayo-tomori", "foden",
  "francesco-acerbi", "francisco-conceicao", "frimpong", "gabriel-jesus",
  "gabriel-magalhaes", "gabriel-martinelli", "garnacho", "gavi",
  "giorgi-mamardashvili", "giovanni-leoni", "giuliano-simeone", "goncalo-ramos",
  "gonzalo-garcia", "gordon", "grimaldo", "gvardiol",
  "gyokeres", "haaland", "hakan-calhanoglu", "hakimi",
  "harvey-elliott", "hincapie", "hojlund", "inigo-martinez",
  "isak", "jakub-kiwior", "james-trafford", "jarell-quansah",
  "jeremy-doku", "joan-garcia", "joao-neves", "joao-palhinha",
  "joe-gomez", "john-stones", "jonathan-david", "jonathan-tah",
  "joshua-zirkzee", "josip-stanisic", "julian-alvarez", "julian-brandt",
  "jurrien-timber", "kai-havertz", "kane", "karim-adeyemi",
  "kenan-yildiz", "kim-min-jae", "kimmich", "kobbie-mainoo",
  "kobel", "konate", "kounde", "kvaratskhelia",
  "lamine-yamal", "lautaro", "leandro-trossard", "leao",
  "lee-kang-in", "leny-yoro", "leon-goretzka", "leroy-sane",
  "levi-colwill", "lewandowski", "liam-delap", "lisandro-martinez",
  "lookman", "lucas-beraldo", "lucas-hernandez", "luis-diaz",
  "luke-shaw", "mac-allister", "maignan", "malo-gusto",
  "manuel-akanji", "manuel-neuer", "marc-bernal", "marc-casado",
  "marc-cucurella", "marcos-llorente", "marcus-rashford", "marmoush",
  "marquinhos", "mateta", "matheus-cunha", "matheus-nunes",
  "mathys-tel", "matvey-safonov", "max-alleyne", "mbappe",
  "messi", "michele-di-gregorio", "mikel-merino", "milos-kerkez",
  "musiala", "myles-lewis-skelly", "nathan-ake", "nico-gonzalez",
  "nico-schlotterbeck", "nico-williams", "noni-madueke", "nuno-mendes",
  "nusa", "nypan", "oblak", "odegaard",
  "oleksandr-zinchenko", "olise", "openda", "oscar-bobb",
  "osimhen", "pacho", "palmer", "patrick-berg",
  "pau-victor", "pedri", "pedro-neto", "pedro-porro",
  "piotr-zielinski", "pope", "ramy-bensebaini", "raphael-guerreiro",
  "raphinha", "raul-asencio", "raya", "rayan-ait-nouri",
  "rayan-cherki", "retegui", "riccardo-calafiori", "rico-lewis",
  "robert-sanchez", "robin-le-normand", "rodri", "rodrygo",
  "romeo-lavia", "rooney-bardghji", "ruben-dias", "ryan-gravenberch",
  "ryerson", "sacha-boey", "saka", "salah",
  "saliba", "sander-berge", "santiago-gimenez", "savinho",
  "serge-gnabry", "serhou-guirassy", "sesko", "solanke",
  "sommer", "son", "stefan-ortega", "strahinja-pavlovic",
  "strand-larsen", "tchouameni", "ter-stegen", "teun-koopmeiners",
  "theo-hernandez", "thorsby", "thuram", "tijjani-reijnders",
  "tom-bischof", "tonali", "trent", "trey-nyoni",
  "valverde", "van-dijk", "vinicius", "vitinha",
  "vlahovic", "waldemar-anton", "warren-zaire-emery", "wataru-endo",
  "watkins", "wirtz", "wojciech-szczesny", "xavi-simons",
  "youssouf-fofana", "zubimendi",
]);

export function playerPhoto(slug: string): string | null {
  return withPhoto.has(slug) ? `/players/${slug}.png` : null;
}
