const flags: Record<string, string> = {
  'haaland': "🇳🇴", 'odegaard': "🇳🇴", 'isak': "🇸🇪", 'gyokeres': "🇸🇪", 'strand-larsen': "🇳🇴", 'nusa': "🇳🇴", 'aursnes': "🇳🇴", 'patrick-berg': "🇳🇴", 'thorsby': "🇳🇴", 'nypan': "🇳🇴", 'ajer': "🇳🇴", 'ryerson': "🇳🇴", 'kobel': "🇨🇭", 'sommer': "🇨🇭", 'alisson': "🇧🇷", 'ederson': "🇧🇷", 'courtois': "🇧🇪", 'donnarumma': "🇮🇹", 'diogo-costa': "🇵🇹", 'raya': "🇪🇸", 'pope': "🏴", 'ter-stegen': "🇩🇪", 'maignan': "🇫🇷", 'oblak': "🇸🇮",
  'mbappe': "🇫🇷", 'vinicius': "🇧🇷", 'rodrygo': "🇧🇷", 'endrick': "🇧🇷", 'bellingham': "🏴", 'rodri': "🇪🇸", 'salah': "🇪🇬", 'van-dijk': "🇳🇱", 'hakimi': "🇲🇦", 'wirtz': "🇩🇪", 'kane': "🏴", 'lewandowski': "🇵🇱", 'lautaro': "🇦🇷", 'osimhen': "🇳🇬", 'vlahovic': "🇷🇸", 'watkins': "🏴", 'retegui': "🇮🇹", 'dovbyk': "🇺🇦", 'thuram': "🇫🇷", 'sesko': "🇸🇮", 'ekitike': "🇫🇷", 'jonathan-david': "🇨🇦", 'lookman': "🇳🇬", 'openda': "🇧🇪", 'mateta': "🇫🇷", 'darwin-nunez': "🇺🇾", 'solanke': "🏴", 'marmoush': "🇪🇬", 'boniface': "🇳🇬", 'hojlund': "🇩🇰", 'gabriel-jesus': "🇧🇷", 'enesyri': "🇲🇦",
  'carvajal': "🇪🇸", 'trent': "🏴", 'frimpong': "🇳🇱", 'kounde': "🇫🇷", 'reece-james': "🏴", 'pedro-porro': "🇪🇸", 'nuno-mendes': "🇵🇹", 'theo-hernandez': "🇫🇷", 'grimaldo': "🇪🇸", 'davies': "🇨🇦", 'dimarco': "🇮🇹", 'gvardiol': "🇭🇷", 'saliba': "🇫🇷", 'ruben-dias': "🇵🇹", 'pacho': "🇪🇨", 'marquinhos': "🇧🇷", 'bastoni': "🇮🇹", 'araujo': "🇺🇾", 'konate': "🇫🇷", 'de-ligt': "🇳🇱", 'cubarsi': "🇪🇸", 'hincapie': "🇪🇨",
  'de-bruyne': "🇧🇪", 'kimmich': "🇩🇪", 'pedri': "🇪🇸", 'vitinha': "🇵🇹", 'declan-rice': "🏴", 'valverde': "🇺🇾", 'musiala': "🇩🇪", 'foden': "🏴", 'bruno-fernandes': "🇵🇹", 'bernardo-silva': "🇵🇹", 'barella': "🇮🇹", 'zubimendi': "🇪🇸", 'mac-allister': "🇦🇷", 'enzo-fernandez': "🇦🇷", 'tonali': "🇮🇹", 'caicedo': "🇪🇨", 'tchouameni': "🇫🇷", 'camavinga': "🇫🇷", 'gavi': "🇪🇸", 'eze': "🏴", 'xavi-simons': "🇳🇱", 'de-jong': "🇳🇱", 'messi': "🇦🇷",
  'lamine-yamal': "🇪🇸", 'saka': "🏴", 'dembele': "🇫🇷", 'raphinha': "🇧🇷", 'son': "🇰🇷", 'leao': "🇵🇹", 'nico-williams': "🇪🇸", 'kvaratskhelia': "🇬🇪", 'savinho': "🇧🇷", 'olise': "🇫🇷", 'coman': "🇫🇷", 'luis-diaz': "🇨🇴", 'gordon': "🏴", 'garnacho': "🇦🇷", 'oscar-bobb': "🇳🇴",
  'manuel-akanji': "🇨🇭", 'nathan-ake': "🇳🇱", 'rico-lewis': "🏴", 'rayan-ait-nouri': "🇩🇿", 'matheus-nunes': "🇵🇹", 'nico-gonzalez': "🇪🇸", 'rayan-cherki': "🇫🇷", 'jeremy-doku': "🇧🇪", 'claudio-echeverri': "🇦🇷", 'abdukodir-khusanov': "🇺🇿", 'antoine-semenyo': "🇬🇭",
  'joan-garcia': "🇪🇸", 'wojciech-szczesny': "🇵🇱", 'alejandro-balde': "🇪🇸", 'eric-garcia': "🇪🇸", 'inigo-martinez': "🇪🇸", 'dani-olmo': "🇪🇸", 'fermin-lopez': "🇪🇸", 'marc-casado': "🇪🇸", 'ferran-torres': "🇪🇸", 'marc-bernal': "🇪🇸", 'rooney-bardghji': "🇸🇪", 'andreas-christensen': "🇩🇰", 'marcus-rashford': "🏴",
  'manuel-neuer': "🇩🇪", 'dayot-upamecano': "🇫🇷", 'kim-min-jae': "🇰🇷", 'jonathan-tah': "🇩🇪", 'raphael-guerreiro': "🇵🇹", 'josip-stanisic': "🇭🇷", 'aleksandar-pavlovic': "🇩🇪", 'joao-palhinha': "🇵🇹", 'leon-goretzka': "🇩🇪", 'serge-gnabry': "🇩🇪", 'leroy-sane': "🇩🇪", 'sacha-boey': "🇫🇷", 'mathys-tel': "🇫🇷", 'tom-bischof': "🇩🇪",
  'giorgi-mamardashvili': "🇬🇪", 'andrew-robertson': "🏴", 'conor-bradley': "🇬🇧", 'joe-gomez': "🏴", 'milos-kerkez': "🇭🇺", 'ryan-gravenberch': "🇳🇱", 'dominik-szoboszlai': "🇭🇺", 'curtis-jones': "🏴", 'cody-gakpo': "🇳🇱", 'federico-chiesa': "🇮🇹", 'harvey-elliott': "🏴", 'wataru-endo': "🇯🇵", 'giovanni-leoni': "🇮🇹",
  'eder-militao': "🇧🇷", 'david-alaba': "🇦🇹", 'ferland-mendy': "🇫🇷", 'fran-garcia': "🇪🇸", 'dean-huijsen': "🇪🇸", 'raul-asencio': "🇪🇸", 'arda-guler': "🇹🇷", 'brahim-diaz': "🇲🇦", 'gonzalo-garcia': "🇪🇸", 'andriy-lunin': "🇺🇦",
  'desire-doue': "🇫🇷", 'bradley-barcola': "🇫🇷", 'joao-neves': "🇵🇹", 'fabian-ruiz': "🇪🇸", 'warren-zaire-emery': "🇫🇷", 'lee-kang-in': "🇰🇷", 'lucas-hernandez': "🇫🇷", 'lucas-beraldo': "🇧🇷", 'matvey-safonov': "🇷🇺", 'goncalo-ramos': "🇵🇹", 'marc-cucurella': "🇪🇸", 'levi-colwill': "🏴", 'wesley-fofana': "🇫🇷", 'malo-gusto': "🇫🇷", 'romeo-lavia': "🇧🇪", 'pedro-neto': "🇵🇹", 'estevao': "🇧🇷", 'liam-delap': "🏴", 'robert-sanchez': "🇪🇸",
  'andre-onana': "🇨🇲", 'lisandro-martinez': "🇦🇷", 'leny-yoro': "🇫🇷", 'diogo-dalot': "🇵🇹", 'luke-shaw': "🏴", 'kobbie-mainoo': "🏴", 'amad-diallo': "🇨🇮", 'matheus-cunha': "🇧🇷", 'bryan-mbeumo': "🇨🇲", 'joshua-zirkzee': "🇳🇱", 'casemiro': "🇧🇷", 'denzel-dumfries': "🇳🇱", 'hakan-calhanoglu': "🇹🇷", 'benjamin-pavard': "🇫🇷", 'carlos-augusto': "🇧🇷",
};

export function playerFlag(slug: string | null) { return slug ? flags[slug] ?? "🌐" : "🌐"; }

