"use client";

import { useActionState } from "react";
import type { ActionState } from "@/lib/actions";
import { buyNowMarketAction, counterDirectTransferOfferAction, createMarketListingAction, placeMarketBidAction, respondDirectTransferOfferAction, sendDirectTransferOfferAction } from "@/lib/market-actions";
import { buttonClass, cardClass, secondaryButtonClass } from "./ui";

type Card = { id: string; name: string; position: string; overall: number; tradable: boolean; acquired_price: number };
type Friend = { id: string; username: string };
type Listing = { id: string; starting_price: number; buy_now_price: number; ends_at: string; card: { name: string; position: string; overall: number }; seller_name: string; highest_bid: number | null };
type Offer = { id: string; seller_id: string; buyer_id: string; proposed_by: string; price: number; card: { name: string; position: string; overall: number }; seller_name: string; buyer_name: string };
const initial: ActionState = {};

function priceRange(card: Card) { return { min: Math.ceil(card.acquired_price * .7), max: Math.floor(card.acquired_price * 1.3) }; }
function ListCard({ card }: { card: Card }) {
  const [state, action, pending] = useActionState(createMarketListingAction, initial); const { min, max } = priceRange(card);
  if (!card.tradable) return null;
  return <form action={action} className="grid gap-2 rounded-lg border border-border p-3 sm:grid-cols-[1fr_90px_90px_90px_auto]"><div><b>{card.name}</b><span className="ml-2 text-sm text-muted">{card.position} · {card.overall}</span></div><input type="hidden" name="card_id" value={card.id}/><input name="start_price" type="number" min={min} max={max} defaultValue={min} aria-label="Startpris"/><input name="buy_now_price" type="number" min={min} max={max} defaultValue={max} aria-label="Kjøp nå-pris"/><select name="duration_hours" defaultValue="24" aria-label="Varighet"><option value="1">1 time</option><option value="6">6 timer</option><option value="24">24 timer</option></select><button className={secondaryButtonClass} disabled={pending}>Legg ut</button>{state.error ? <p className="sm:col-span-5 text-sm text-danger">{state.error}</p> : state.ok ? <p className="sm:col-span-5 text-sm text-success">Kortet ligger ute for vennene dine.</p> : null}</form>;
}

function DirectOfferCard({ card, friends }: { card: Card; friends: Friend[] }) {
  const [state, action, pending] = useActionState(sendDirectTransferOfferAction, initial); const { min, max } = priceRange(card);
  if (!card.tradable) return null;
  return <form action={action} className="grid gap-2 rounded-lg border border-border bg-surface-raised p-3 sm:grid-cols-[1fr_150px_100px_auto]"><div><b>{card.name}</b><span className="ml-2 text-sm text-muted">{card.position} · {card.overall} · Mulig pris {min}–{max} MB</span></div><input type="hidden" name="card_id" value={card.id}/><select name="buyer_id" aria-label="Velg venn"><option value="">Velg venn</option>{friends.map((friend) => <option key={friend.id} value={friend.id}>{friend.username}</option>)}</select><input name="price" type="number" min={min} max={max} defaultValue={max} aria-label="Pris"/><button className={buttonClass} disabled={pending}>Send tilbud</button>{state.error ? <p className="sm:col-span-4 text-sm text-danger">{state.error}</p> : state.ok ? <p className="sm:col-span-4 text-sm text-success">Tilbudet er sendt. Vennen din kan godta, avslå eller foreslå en ny pris.</p> : null}</form>;
}

function MarketListing({ listing, budget }: { listing: Listing; budget: number }) {
  const [bidState, bidAction, bidding] = useActionState(placeMarketBidAction, initial); const [buyState, buyAction, buying] = useActionState(buyNowMarketAction, initial);
  const minimum = Math.max(listing.starting_price, (listing.highest_bid ?? 0) + 1);
  return <article className="rounded-xl border border-border bg-surface-raised p-4"><div className="flex justify-between"><div><p className="text-xs font-bold text-muted">{listing.card.position}</p><h3 className="font-bold">{listing.card.name}</h3><p className="text-sm text-muted">Fra {listing.seller_name}</p></div><b className="text-3xl">{listing.card.overall}</b></div><p className="mt-3 text-sm">Høyeste bud: <b>{listing.highest_bid ?? "Ingen"}</b> · Kjøp nå: <b className="text-accent">{listing.buy_now_price} MB</b></p><div className="mt-3 flex gap-2"><form action={bidAction} className="flex min-w-0 flex-1 gap-2"><input type="hidden" name="listing_id" value={listing.id}/><input className="min-w-0 w-full" name="amount" type="number" min={minimum} defaultValue={minimum}/><button className={secondaryButtonClass} disabled={bidding || budget < minimum}>By</button></form><form action={buyAction}><input type="hidden" name="listing_id" value={listing.id}/><button className={buttonClass} disabled={buying || budget < listing.buy_now_price}>Kjøp nå</button></form></div>{bidState.error || buyState.error ? <p className="mt-2 text-sm text-danger">{bidState.error ?? buyState.error}</p> : bidState.ok || buyState.ok ? <p className="mt-2 text-sm text-success">Markedet er oppdatert.</p> : null}</article>;
}

function OfferCard({ offer, userId, budget }: { offer: Offer; userId: string; budget: number }) {
  const [responseState, responseAction, responding] = useActionState(respondDirectTransferOfferAction, initial); const [counterState, counterAction, countering] = useActionState(counterDirectTransferOfferAction, initial);
  const recipient = offer.proposed_by !== userId; const otherName = offer.seller_id === userId ? offer.buyer_name : offer.seller_name; const buyerNeedsBudget = offer.buyer_id === userId;
  return <article className="rounded-xl border border-accent/40 bg-accent-soft p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-muted">{recipient ? "Krever svar" : "Venter på svar"}</p><h3 className="mt-1 font-bold">{offer.card.name} <span className="text-sm font-normal text-muted">{offer.card.position} · {offer.card.overall}</span></h3><p className="mt-1 text-sm text-muted">{recipient ? `${otherName} har sendt deg et tilbud.` : `Tilbud sendt til ${otherName}.`}</p></div><b className="text-2xl text-accent">{offer.price} MB</b></div><p className="mt-3 text-xs text-muted">Ved salg mottar selger 95 % etter overgangsavgift.</p>{recipient ? <div className="mt-3 grid gap-2 sm:grid-cols-[auto_auto_1fr]"><form action={responseAction}><input type="hidden" name="offer_id" value={offer.id}/><button className={buttonClass} name="response" value="accept" disabled={responding || (buyerNeedsBudget && budget < offer.price)}>Godta</button></form><form action={responseAction}><input type="hidden" name="offer_id" value={offer.id}/><button className={secondaryButtonClass} name="response" value="decline" disabled={responding}>Avslå</button></form><form action={counterAction} className="flex gap-2"><input type="hidden" name="offer_id" value={offer.id}/><input className="min-w-0 flex-1" name="price" type="number" min="1" defaultValue={offer.price} aria-label="Motpris"/><button className={secondaryButtonClass} disabled={countering}>Motbud</button></form></div> : null}{responseState.error || counterState.error ? <p className="mt-2 text-sm text-danger">{responseState.error ?? counterState.error}</p> : responseState.ok || counterState.ok ? <p className="mt-2 text-sm text-success">Tilbudet er oppdatert.</p> : null}</article>;
}

export function FriendMarket({ cards, listings, offers, friends, userId, budget }: { cards: Card[]; listings: Listing[]; offers: Offer[]; friends: Friend[]; userId: string; budget: number }) {
  const tradable = cards.filter((card) => card.tradable); const incoming = offers.filter((offer) => offer.proposed_by !== userId).length;
  return <section className={`${cardClass} grid gap-5`}><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-semibold">Overgangsmarked</h2><p className="text-sm text-muted">Bare vennene dine kan se annonser, bud og direkte tilbud.</p></div>{incoming ? <b className="rounded-full bg-accent-soft px-3 py-1 text-sm text-accent">{incoming} tilbud venter</b> : null}</div><div className="grid gap-2"><h3 className="text-sm font-bold uppercase text-muted">Direkte tilbud til en venn</h3>{friends.length === 0 ? <p className="text-sm text-muted">Legg til en venn for å forhandle direkte.</p> : tradable.length ? tradable.map((card) => <DirectOfferCard key={card.id} card={card} friends={friends}/>) : <p className="text-sm text-muted">Du trenger et kjøpt kort før du kan sende tilbud.</p>}</div><div className="grid gap-3"><h3 className="text-sm font-bold uppercase text-muted">Direkte tilbud</h3>{offers.length ? <div className="grid gap-3 sm:grid-cols-2">{offers.map((offer) => <OfferCard key={offer.id} offer={offer} userId={userId} budget={budget}/>)}</div> : <p className="text-sm text-muted">Ingen aktive direkte tilbud.</p>}</div><div className="grid gap-2"><h3 className="text-sm font-bold uppercase text-muted">Legg ut eget kort</h3>{tradable.length ? tradable.map((card) => <ListCard key={card.id} card={card}/>) : <p className="text-sm text-muted">Du trenger et kjøpt kort før du kan legge noe ut.</p>}</div><div className="grid gap-3"><h3 className="text-sm font-bold uppercase text-muted">Venners annonser</h3>{listings.length ? <div className="grid gap-3 sm:grid-cols-2">{listings.map((listing) => <MarketListing key={listing.id} listing={listing} budget={budget}/>)}</div> : <p className="text-sm text-muted">Ingen aktive annonser fra vennene dine ennå.</p>}</div></section>;
}
