"use client";

import { useActionState } from "react";
import Image from "next/image";
import { deleteAccountAction, updateProfileAction, uploadAvatarAction, type AuthActionState } from "@/lib/auth-actions";
import { buttonClass, cardClass, labelClass, secondaryButtonClass } from "./ui";

const initialState: AuthActionState = {};

export function ProfileForms({ username, avatarUrl }: { username: string; avatarUrl: string | null }) {
  const [nameState, nameAction, changingName] = useActionState(updateProfileAction, initialState);
  const [avatarState, avatarAction, uploading] = useActionState(uploadAvatarAction, initialState);
  const [deleteState, deleteAction, deleting] = useActionState(deleteAccountAction, initialState);
  return <div className="grid gap-6"><section className={`${cardClass} grid gap-4`}><h2 className="text-lg font-semibold">Profilbilde</h2>{avatarUrl ? <Image src={avatarUrl} alt="Profilbilde" width={80} height={80} className="h-20 w-20 rounded-full object-cover" /> : <div className="flex h-20 w-20 items-center justify-center rounded-full bg-accent-soft text-2xl font-semibold text-accent">{username.slice(0, 1).toUpperCase()}</div>}<form action={avatarAction} className="grid gap-3"><input name="avatar" type="file" accept="image/png,image/jpeg,image/webp" required />{avatarState.error ? <p className="text-danger">{avatarState.error}</p> : null}{avatarState.message ? <p className="text-success">{avatarState.message}</p> : null}<button className={secondaryButtonClass} disabled={uploading}>{uploading ? "Laster opp…" : "Legg til eller endre profilbilde"}</button></form></section><section className={`${cardClass} grid gap-4`}><h2 className="text-lg font-semibold">Brukernavn</h2><form action={nameAction} className="grid gap-3"><div><label className={labelClass} htmlFor="profile-username">Nytt brukernavn</label><input id="profile-username" name="username" defaultValue={username} className="mt-1 w-full" required /></div><div><label className={labelClass} htmlFor="current-code">Sekssifret kode</label><input id="current-code" name="current_code" type="tel" inputMode="numeric" pattern="[0-9]*" maxLength={6} className="mt-1 w-full tracking-[0.35em]" required /></div>{nameState.error ? <p className="text-danger">{nameState.error}</p> : null}{nameState.message ? <p className="text-success">{nameState.message}</p> : null}<button className={buttonClass} disabled={changingName}>{changingName ? "Lagrer…" : "Lagre brukernavn"}</button></form></section><section className={`${cardClass} grid gap-4 border-danger`}><h2 className="text-lg font-semibold text-danger">Slett konto</h2><p className="text-sm text-muted">Fullførte turneringer beholdes anonymt. Aktive turneringer må lukkes, slettes eller overføres først.</p><form action={deleteAction} className="grid gap-3"><input name="code" type="tel" inputMode="numeric" pattern="[0-9]*" maxLength={6} placeholder="Sekssifret kode" required />{deleteState.error ? <p className="text-danger">{deleteState.error}</p> : null}<button className="rounded-lg border border-danger px-4 py-2 font-medium text-danger" disabled={deleting}>{deleting ? "Sletter…" : "Slett konto"}</button></form></section></div>;
}
